//! Hybrid Execution Mode
//!
//! Cloud brain plans multi-step tasks, local brain executes each step.
//! This provides the best of both worlds:
//! - Cloud: Large context, complex planning, multi-step reasoning
//! - Local: Fast execution, privacy for sensitive data, zero API cost per step
//!
//! Architecture:
//! 1. Cloud brain generates structured plan (list of steps with dependencies)
//! 2. DAG executor runs steps concurrently where possible
//! 3. Each step executed by local brain (if available) or cloud fallback
//! 4. Sensitive data never sent to cloud during execution

use crate::conductor::types::{ConductorPlan, PlanStep};
use crate::llm::router::LLMRouter;
use crate::llm::{LLMResponse, Message};
use anyhow::{Context, Result};
use brain::reasoning::LocalBrain;
use sdk::Brain;
use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{debug, info, warn};

/// Hybrid execution coordinator
///
/// Manages the split between cloud planning and local execution
pub struct HybridExecutor {
    /// LLM router for cloud planning
    router: Arc<LLMRouter>,

    /// Optional local brain for step execution
    local_brain: Option<Arc<LocalBrain>>,

    /// Step execution results (shared across concurrent tasks)
    results: Arc<RwLock<HashMap<String, StepExecutionResult>>>,
}

/// Result of executing a single step
#[derive(Debug, Clone)]
pub struct StepExecutionResult {
    pub step_id: String,
    pub success: bool,
    pub output: String,
    pub execution_time_ms: u64,
    pub executed_by: ExecutionLocation,
}

/// Where the step was executed
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExecutionLocation {
    LocalBrain,
    Cloud,
}

impl HybridExecutor {
    /// Create a new hybrid executor
    pub fn new(router: Arc<LLMRouter>, local_brain: Option<Arc<LocalBrain>>) -> Self {
        Self {
            router,
            local_brain,
            results: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    /// Generate a plan using cloud brain
    ///
    /// Cloud brain has larger context and better planning capabilities
    pub async fn plan_with_cloud(&self, goal: &str, context: &str) -> Result<ConductorPlan> {
        info!("Planning with cloud brain: {}", goal);

        let system = Message::system(
            "You are a task planner. Break down the user's goal into discrete, executable steps.\n\
            Output ONLY a JSON array of steps. Each step must have:\n\
            - \"id\": unique identifier (e.g., \"step_1\")\n\
            - \"description\": what to do in this step\n\
            - \"dependencies\": array of step IDs this depends on (empty for independent steps)\n\
            - \"expected_outcome\": success criteria\n\n\
            Make steps as independent as possible to enable parallel execution.\n\
            Keep steps small and focused (1-2 actions per step).\n\n\
            Example:\n\
            [{\"id\":\"step_1\",\"description\":\"Read config.toml\",\"dependencies\":[],\"expected_outcome\":\"Config loaded\"},\
            {\"id\":\"step_2\",\"description\":\"Read main.rs\",\"dependencies\":[],\"expected_outcome\":\"Code loaded\"},\
            {\"id\":\"step_3\",\"description\":\"Analyze both files\",\"dependencies\":[\"step_1\",\"step_2\"],\"expected_outcome\":\"Analysis complete\"}]\n\n\
            Output ONLY the JSON array."
        );

        let user = Message::user(format!("Goal: {}\n\nContext:\n{}", goal, context));

        let (response, provider) = self
            .router
            .call(&[system, user])
            .await
            .context("Cloud planning failed")?;

        info!("Plan generated by: {}", provider);

        let content = match response {
            LLMResponse::FinalAnswer(answer) => answer.content,
            LLMResponse::ToolCall(_) => {
                return Err(anyhow::anyhow!("Expected plan, got tool call"));
            }
        };

        // Parse plan from JSON
        self.parse_plan(&content, goal)
    }

    /// Execute a plan using hybrid mode
    ///
    /// Steps are executed by local brain if available, cloud as fallback
    pub async fn execute_plan(
        &self,
        plan: &ConductorPlan,
    ) -> Result<HashMap<String, StepExecutionResult>> {
        info!("Executing plan: {} ({} steps)", plan.id, plan.steps.len());

        // Build dependency graph
        let dag = self.build_dag(&plan.steps)?;

        // Execute steps in topological order with concurrency
        self.execute_dag(&dag, &plan.steps).await?;

        // Return all results
        let results = self.results.read().await;
        Ok(results.clone())
    }

    /// Execute a single step using local brain (preferred) or cloud fallback
    async fn execute_step(&self, step: &PlanStep, context: &str) -> Result<StepExecutionResult> {
        let start = std::time::Instant::now();

        // Try local brain first if available
        if let Some(local_brain) = &self.local_brain {
            if local_brain.check_available().await {
                debug!("Executing step {} with local brain", step.id);

                match self.execute_with_local(local_brain, step, context).await {
                    Ok(output) => {
                        let elapsed = start.elapsed().as_millis() as u64;
                        info!("Step {} completed by local brain in {}ms", step.id, elapsed);

                        return Ok(StepExecutionResult {
                            step_id: step.id.clone(),
                            success: true,
                            output,
                            execution_time_ms: elapsed,
                            executed_by: ExecutionLocation::LocalBrain,
                        });
                    }
                    Err(e) => {
                        warn!("Local brain failed for step {}: {}", step.id, e);
                        // Fall through to cloud execution
                    }
                }
            }
        }

        // Fallback to cloud execution
        debug!("Executing step {} with cloud", step.id);
        let output = self.execute_with_cloud(step, context).await?;
        let elapsed = start.elapsed().as_millis() as u64;

        info!("Step {} completed by cloud in {}ms", step.id, elapsed);

        Ok(StepExecutionResult {
            step_id: step.id.clone(),
            success: true,
            output,
            execution_time_ms: elapsed,
            executed_by: ExecutionLocation::Cloud,
        })
    }

    /// Execute step with local brain
    async fn execute_with_local(
        &self,
        local_brain: &Arc<LocalBrain>,
        step: &PlanStep,
        context: &str,
    ) -> Result<String> {
        let system = format!(
            "Execute this step: {}\n\
            Expected outcome: {}\n\n\
            Context from previous steps:\n{}",
            step.description, step.expected_outcome, context
        );

        let messages = vec![sdk::Message {
            role: "user".to_string(),
            content: step.description.clone(),
        }];

        let response = local_brain
            .complete(&system, &messages, &[])
            .await
            .context("Local brain execution failed")?;

        Ok(response.content)
    }

    /// Execute step with cloud
    async fn execute_with_cloud(&self, step: &PlanStep, context: &str) -> Result<String> {
        let system = Message::system(format!(
            "Execute this step: {}\n\
            Expected outcome: {}\n\n\
            Context from previous steps:\n{}",
            step.description, step.expected_outcome, context
        ));

        let user = Message::user(&step.description);

        let (response, _) = self
            .router
            .call(&[system, user])
            .await
            .context("Cloud execution failed")?;

        match response {
            LLMResponse::FinalAnswer(answer) => Ok(answer.content),
            LLMResponse::ToolCall(call) => {
                Ok(format!("Tool call: {}({})", call.name, call.arguments))
            }
        }
    }

    /// Build dependency graph (DAG) from steps
    pub fn build_dag(&self, steps: &[PlanStep]) -> Result<HashMap<String, Vec<String>>> {
        let mut dag: HashMap<String, Vec<String>> = HashMap::new();

        for step in steps {
            dag.insert(step.id.clone(), step.dependencies.clone());
        }

        // Verify no cycles
        self.verify_acyclic(&dag)?;

        Ok(dag)
    }

    /// Verify DAG has no cycles
    fn verify_acyclic(&self, dag: &HashMap<String, Vec<String>>) -> Result<()> {
        let mut visited = HashSet::new();
        let mut rec_stack = HashSet::new();

        for node in dag.keys() {
            if self.has_cycle(node, dag, &mut visited, &mut rec_stack) {
                return Err(anyhow::anyhow!("Cycle detected in dependency graph"));
            }
        }

        Ok(())
    }

    /// DFS cycle detection
    fn has_cycle(
        &self,
        node: &str,
        dag: &HashMap<String, Vec<String>>,
        visited: &mut HashSet<String>,
        rec_stack: &mut HashSet<String>,
    ) -> bool {
        if rec_stack.contains(node) {
            return true;
        }

        if visited.contains(node) {
            return false;
        }

        visited.insert(node.to_string());
        rec_stack.insert(node.to_string());

        if let Some(deps) = dag.get(node) {
            for dep in deps {
                if self.has_cycle(dep, dag, visited, rec_stack) {
                    return true;
                }
            }
        }

        rec_stack.remove(node);
        false
    }

    /// Execute DAG with concurrency
    ///
    /// Steps with no pending dependencies run concurrently
    async fn execute_dag(
        &self,
        dag: &HashMap<String, Vec<String>>,
        steps: &[PlanStep],
    ) -> Result<()> {
        let mut completed = HashSet::new();
        let mut pending: HashSet<String> = dag.keys().cloned().collect();

        while !pending.is_empty() {
            // Find steps ready to execute (all dependencies completed)
            let ready: Vec<String> = pending
                .iter()
                .filter(|step_id| {
                    let Some(deps) = dag.get(step_id.as_str()) else {
                        return false;
                    };
                    deps.iter().all(|dep| completed.contains(dep))
                })
                .cloned()
                .collect();

            if ready.is_empty() {
                return Err(anyhow::anyhow!("Deadlock: no steps ready to execute"));
            }

            info!("Executing {} steps concurrently: {:?}", ready.len(), ready);

            // Execute ready steps concurrently
            let mut handles = vec![];

            for step_id in &ready {
                let step = steps
                    .iter()
                    .find(|s| &s.id == step_id)
                    .ok_or_else(|| anyhow::anyhow!("Step not found: {}", step_id))?
                    .clone();

                // Build context from completed dependencies
                let context = self.build_context(&step.dependencies).await;

                let executor = self.clone_for_task();
                let handle =
                    tokio::spawn(async move { executor.execute_step(&step, &context).await });

                handles.push((step_id.clone(), handle));
            }

            // Wait for all concurrent steps to complete
            for (step_id, handle) in handles {
                match handle.await {
                    Ok(Ok(result)) => {
                        self.results.write().await.insert(step_id.clone(), result);
                        completed.insert(step_id.clone());
                        pending.remove(&step_id);
                    }
                    Ok(Err(e)) => {
                        warn!("Step {} failed: {}", step_id, e);
                        return Err(e);
                    }
                    Err(e) => {
                        warn!("Step {} panicked: {}", step_id, e);
                        return Err(anyhow::anyhow!("Step {} panicked", step_id));
                    }
                }
            }
        }

        Ok(())
    }

    /// Build context string from completed dependency results
    async fn build_context(&self, dependencies: &[String]) -> String {
        let results = self.results.read().await;

        dependencies
            .iter()
            .filter_map(|dep_id| results.get(dep_id))
            .map(|result| format!("[{}]: {}", result.step_id, result.output))
            .collect::<Vec<_>>()
            .join("\n\n")
    }

    /// Clone executor for concurrent task execution
    fn clone_for_task(&self) -> Self {
        Self {
            router: self.router.clone(),
            local_brain: self.local_brain.clone(),
            results: self.results.clone(),
        }
    }

    /// Parse plan JSON from LLM response
    pub fn parse_plan(&self, content: &str, goal: &str) -> Result<ConductorPlan> {
        use crate::conductor::types::StepType;

        // Extract JSON array
        let json_str = if let Some(start) = content.find('[') {
            if let Some(end) = content.rfind(']') {
                &content[start..=end]
            } else {
                content
            }
        } else {
            content
        };

        #[derive(serde::Deserialize)]
        struct RawStep {
            id: String,
            description: String,
            #[serde(default)]
            dependencies: Vec<String>,
            expected_outcome: String,
        }

        let raw_steps: Vec<RawStep> =
            serde_json::from_str(json_str).context("Failed to parse plan JSON")?;

        let steps = raw_steps
            .into_iter()
            .enumerate()
            .map(|(i, raw)| PlanStep {
                id: raw.id,
                order: i as u32,
                description: raw.description,
                step_type: StepType::Execute,
                dependencies: raw.dependencies,
                expected_outcome: raw.expected_outcome,
            })
            .collect();

        Ok(ConductorPlan {
            id: uuid::Uuid::new_v4().to_string(),
            original_goal: goal.to_string(),
            mode: Default::default(),
            stages: vec![],
            steps,
            created_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map_err(|e| anyhow::anyhow!("System time error: {}", e))?
                .as_secs() as i64,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conductor::types::StepType;
    use crate::config::LLMConfig;

    fn make_test_step(id: &str, deps: Vec<String>) -> PlanStep {
        PlanStep {
            id: id.to_string(),
            order: 0,
            description: format!("Step {}", id),
            step_type: StepType::Execute,
            dependencies: deps,
            expected_outcome: "Done".to_string(),
        }
    }

    #[test]
    fn test_dag_no_cycles() {
        let config = Arc::new(LLMConfig {
            default_provider: "ollama".to_string(),
            sensitivity_threshold: 0.7,
            complexity_threshold: 0.8,
            ollama: Default::default(),
            openai: Default::default(),
            anthropic: Default::default(),
            gemini: Default::default(),
            nvidia_nim: Default::default(),
            custom_providers: vec![],
        });
        let router = Arc::new(LLMRouter::new(vec![], config));
        let executor = HybridExecutor::new(router, None);

        let steps = vec![
            make_test_step("step_1", vec![]),
            make_test_step("step_2", vec!["step_1".to_string()]),
            make_test_step("step_3", vec!["step_2".to_string()]),
        ];

        let dag = executor.build_dag(&steps).unwrap();
        assert_eq!(dag.len(), 3);
    }

    #[test]
    fn test_dag_detects_cycle() {
        let config = Arc::new(LLMConfig {
            default_provider: "ollama".to_string(),
            sensitivity_threshold: 0.7,
            complexity_threshold: 0.8,
            ollama: Default::default(),
            openai: Default::default(),
            anthropic: Default::default(),
            gemini: Default::default(),
            nvidia_nim: Default::default(),
            custom_providers: vec![],
        });
        let router = Arc::new(LLMRouter::new(vec![], config));
        let executor = HybridExecutor::new(router, None);

        let mut dag = HashMap::new();
        dag.insert("step_1".to_string(), vec!["step_2".to_string()]);
        dag.insert("step_2".to_string(), vec!["step_1".to_string()]);

        let result = executor.verify_acyclic(&dag);
        assert!(result.is_err());
    }

    #[test]
    fn test_dag_parallel_steps() {
        let config = Arc::new(LLMConfig {
            default_provider: "ollama".to_string(),
            sensitivity_threshold: 0.7,
            complexity_threshold: 0.8,
            ollama: Default::default(),
            openai: Default::default(),
            anthropic: Default::default(),
            gemini: Default::default(),
            nvidia_nim: Default::default(),
            custom_providers: vec![],
        });
        let router = Arc::new(LLMRouter::new(vec![], config));
        let executor = HybridExecutor::new(router, None);

        // step_1 and step_2 can run in parallel, step_3 depends on both
        let steps = vec![
            make_test_step("step_1", vec![]),
            make_test_step("step_2", vec![]),
            make_test_step("step_3", vec!["step_1".to_string(), "step_2".to_string()]),
        ];

        let dag = executor.build_dag(&steps).unwrap();
        assert_eq!(dag.get("step_3").unwrap().len(), 2);
    }
}
