use serde::{Deserialize, Serialize};

// Re-export TaskDomain from SDK (moved to shared types)
pub use sdk::TaskDomain;

/// Available step execution status indicators
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StepResult {
    Success,
    Failed(String),
}

/// The local type of step that the conductor is executing
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum StepType {
    #[default]
    Execute,
    Research,
    Verify,
}

/// Specialist role assigned to a plan step.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum StepRole {
    Researcher,
    #[default]
    Executor,
    Verifier,
}

impl StepRole {
    pub fn for_step_type(step_type: &StepType) -> Self {
        match step_type {
            StepType::Research => Self::Researcher,
            StepType::Verify => Self::Verifier,
            StepType::Execute => Self::Executor,
        }
    }
}

/// Routing constraint for a DAG node.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum RoutePolicy {
    LocalOnly,
    LocalPreferred,
    CloudOnly,
    #[default]
    Inherit,
}

/// Represents an individual step within a task plan
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: String,
    pub order: u32,
    pub step_type: StepType,
    #[serde(default)]
    pub role: StepRole,
    #[serde(default)]
    pub parallel_safe: bool,
    #[serde(default)]
    pub route_policy: RoutePolicy,
    pub dependencies: Vec<String>,
    pub description: String,
    pub expected_outcome: String,
}

/// Describes the environment routing behavior for a task chunk
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum ExecutionMode {
    #[default]
    Direct,
    Reflective,
    DeepResearch,
}

/// Stores stage information limits and tools
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Stage {
    pub name: String,
    pub description: String,
    pub tools_allowed: Vec<String>,
}

/// Structure modeling the layout generated by the planner
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConductorPlan {
    pub id: String,
    pub original_goal: String,
    pub mode: ExecutionMode,
    pub stages: Vec<Stage>,
    pub steps: Vec<PlanStep>,
    pub created_at: i64,
}

/// Budgets representing token amounts per memory layer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryBudget {
    pub session_tokens: usize,
    pub system_tokens: usize,
    pub episodic_tokens: usize,
    pub project_tokens: usize,
}

impl Default for MemoryBudget {
    fn default() -> Self {
        Self {
            session_tokens: 8000,
            system_tokens: 4000,
            episodic_tokens: 16000,
            project_tokens: 32000,
        }
    }
}

/// Determines which memory layers are active for a given task domain.
#[derive(Debug, Clone, Copy)]
pub struct ContextLayers {
    pub episodic: bool,
    pub insights: bool,
    pub task_trace: bool,
    pub project: bool,
}

impl ContextLayers {
    pub fn for_domain(domain: &TaskDomain) -> Self {
        match domain {
            TaskDomain::Code => Self {
                episodic: true,
                insights: true,
                task_trace: true,
                project: true,
            },
            TaskDomain::Git => Self {
                episodic: true,
                insights: true,
                task_trace: true,
                project: false,
            },
            TaskDomain::Shell => Self {
                episodic: false,
                insights: false,
                task_trace: true,
                project: false,
            },
            TaskDomain::General => Self {
                episodic: true,
                insights: true,
                task_trace: false,
                project: false,
            },
            TaskDomain::Browser | TaskDomain::Data => Self {
                episodic: true,
                insights: false,
                task_trace: false,
                project: false,
            },
        }
    }
}

/// Type of memory hit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HitType {
    Episodic,
    Insight,
    KnowledgeGraph,
    TaskTrace,
}

/// Result of a memory query.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryHit {
    pub id: String,
    pub source: String,
    pub content: String,
    pub rank: f64,
    pub hit_type: HitType,
    pub importance: f32,
    pub created_at: i64,
    pub final_score: f32,
}

/// Result of an ingest operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestResult {
    pub memory_id: String,
    pub summary: String,
    pub entities: Vec<String>,
    pub topics: Vec<String>,
    pub importance: f64,
}

/// Result of a consolidation operation.
#[derive(Debug, Clone)]
pub enum ConsolidationResult {
    Skipped {
        reason: String,
    },
    Completed {
        memories_processed: usize,
        insights_generated: usize,
    },
}

/// Structured extraction from the ingest prompt.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct IngestExtraction {
    pub summary: String,
    pub entities: Vec<String>,
    pub topics: Vec<String>,
    pub importance: f64,
}

/// Structured insight from the consolidation prompt.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct ConsolidationInsight {
    pub insight: String,
    pub source_ids: Vec<String>,
}
