use serde::{Deserialize, Serialize};

// Re-export TaskDomain from SDK (moved to shared types)
pub use sdk::TaskDomain;

/// Available step execution status indicators
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StepResult {
    Success,
    Failed(String),
}

/// The local type of step that the conductor is executing
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum StepType {
    #[default]
    Execute,
    Research,
    Verify,
}

/// Represents an individual step within a task plan
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: String,
    pub order: u32,
    pub step_type: StepType,
    pub dependencies: Vec<String>,
    pub description: String,
    pub expected_outcome: String,
}

/// Describes the environment routing behavior for a task chunk
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum ExecutionMode {
    #[default]
    Direct,
    Reflective,
    DeepResearch,
}

/// Stores stage information limits and tools
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Stage {
    pub name: String,
    pub description: String,
    pub tools_allowed: Vec<String>,
}

/// Structure modeling the layout generated by the planner
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConductorPlan {
    pub id: String,
    pub original_goal: String,
    pub mode: ExecutionMode,
    pub stages: Vec<Stage>,
    pub steps: Vec<PlanStep>,
    pub created_at: i64,
}

/// Budgets representing token amounts per memory layer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryBudget {
    pub session_tokens: usize,
    pub system_tokens: usize,
    pub episodic_tokens: usize,
    pub project_tokens: usize,
}

impl Default for MemoryBudget {
    fn default() -> Self {
        Self {
            session_tokens: 8000,
            system_tokens: 4000,
            episodic_tokens: 16000,
            project_tokens: 32000,
        }
    }
}
